# -*- coding: utf-8 -*-
"""ML_course_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZBNyeJ1qTxPc0oFWKzrxgEXGwtJ8SQ-

The texts are not balanced
Gör om total words


one challenge is that poetic language tends to have similarities like rhymes and alliteration

baseline of 2 texts from the same time
"""

#imports
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
import math
!pip install jarowinkler
from jarowinkler import *
import random

from string import punctuation
line_size = 10000
gram_size =3

#get all the words

romeoAndJulietText = open("shakespeare.txt").readlines()
r = random.randint(0, len(romeoAndJulietText)-line_size) ## randomizing the input
romeoAndJulietText = romeoAndJulietText[r:r+line_size]

miceAndMenText = open("austen.txt").readlines()
r = random.randint(0, len(miceAndMenText)-line_size)
miceAndMenText = miceAndMenText[r:r+line_size]

#romeoAndJulietText = open("romeo_and_juliet_short.txt").readlines()
#miceAndMenText = open("of_mice_and_men_short.txt").readlines()

#romeoAndJulietText = open("romeo_and_juliet_short.txt").readlines()
#miceAndMenText = open("of_mice_and_men_short.txt").readlines()

def remove_punctuation(text):
  punctuations = [",",":", "!", ";", ".",  "?", "'", "]", "[" ]
  for p in punctuations:
    text = text.replace(p, "")
  return text


def tokenize_line(line, lemmatize=True):
  lemmatizer = WordNetLemmatizer()
  words = nltk.word_tokenize(line)
  if lemmatize:
      words = [lemmatizer.lemmatize(word).lower() for word in words]
  return words

def get_tokenized_words(text, lemmatize=True):
  lemmatizer = WordNetLemmatizer()
  tokenized_words = []
  for line in text:
    line = remove_punctuation(line)
    words = tokenize_line(line)

    for word in words:

        if word not in tokenized_words:
            tokenized_words.append(word)
  return tokenized_words


rj_tokenized_words =get_tokenized_words(romeoAndJulietText) # words in mice and men
mm_tokenized_words =get_tokenized_words(miceAndMenText) # words in romeo and juliet

#sanity check
##print(rj_tokenized_words)
##print(mm_tokenized_words)



def get_grams(word, n):
  grams =[]
  if len(word) >= n:
    for i in range(len(word)-n+1):
      grams.append(word[i:i+n])

  return grams

def count_grams(words, gram):
  count =0
  for word in words:
    count+=word.count(gram)
  return count



all_words = []

common_words=[] # words that exist in both texts, these act as dimensions,  927 with current texts
for word in mm_tokenized_words:
  parts = get_grams(word, gram_size)
  for part in parts:
    if part not in all_words:
        all_words.append(part)
  if word in rj_tokenized_words:
    common_words.append(word)
for word in rj_tokenized_words:
    parts = get_grams(word, 3)
    for part in parts:
      if part not in all_words:
          all_words.append(part)

print(len(all_words))
print(len(common_words))

"""
def get_word_vector(word, text, dictionary, lemmatize = True):
  vector = [0]*len(dictionary) # a vector of 0s

  total_words= 0
  for line in text:
    words = tokenize_line(line)
    total_words+=len(words)

  for line in text:
    words = tokenize_line(line)

    if word in words:
      for i in range(len(dictionary)):
        count = words.count(dictionary[i])
        vector[i]+=count/total_words

  print(word)
  return vector
"""
def get_word_vector(word, text, dictionary, lemmatize = True):
  vector = [0]*len(dictionary) # a vector of 0s

  total_words= 0
  for line in text:
    words = tokenize_line(line)
    total_words+=len(words)

  for line in text:
    words = tokenize_line(line)

    if word in words:
      for i in range(len(dictionary)):
        count = count_grams(words, dictionary[i])
        #vector[i]+=count/total_words
        vector[i]+=count

  #print(word)
  #print(vector)
  return vector



# cosine similarity and word-similarity...can add tfidf later
def cosine_similarity(word, old_text, new_text, dictionary, lemmatize = True, tfidf=False):
  # get vectors
  old_vector=get_word_vector(word, romeoAndJulietText, all_words)
  new_vector=get_word_vector(word, miceAndMenText, all_words)

  #calculate similarity
  dotprod =0
  squaredA = 0
  squaredB = 0
  for i in range(len(old_vector)):
    dotprod+=old_vector[i]*new_vector[i]
    squaredA+=old_vector[i]**2
    squaredB+=new_vector[i]**2

  lengths = math.sqrt(squaredA)*math.sqrt(squaredB)
  try:
    similarity = dotprod/lengths
  except Exception as e:
    print(e)
    similarity = 0
  return similarity

def cosine_similarities(words, old_text, new_text, dictionary, lemmatize = True, tfidf=False):
  scores = []
  for word in words:
    score = cosine_similarity(word, old_text, new_text, dictionary, lemmatize, tfidf)
    #print(word, score)
    scores.append(score)
  return scores

# how much similarity in spelling is there. Use the average
def calculate_ortogaphic_similarity(word, context):
  scores = []
  for c in context:
    if word != c:
      score = jarowinkler_similarity(word, c)
      scores.append(score)

  #return max(scores)
  if len(scores) == 0:
    return 0
  else:
    return sum(scores) / len(scores)

# calculating the ortographic similarty of all the common words based on the old text
def calculate_ortogaphic_similarities(words, text):
  scores = []
  for word in common_words:
    word_scores=[]
    for line in text:
      words = tokenize_line(line)
      #print(word, words)
      score = calculate_ortogaphic_similarity(word, words)
      word_scores.append(score)
    scores.append(sum(word_scores) / len(word_scores))

  return scores
print("Calculating ortographic similarity")
ort_similarity_scores = calculate_ortogaphic_similarities(common_words, romeoAndJulietText)

print("Calculating cosine similarity")
cosine_similarity_scores = cosine_similarities(common_words, romeoAndJulietText, miceAndMenText, all_words)


print("Ortographic similarity:")
print(ort_similarity_scores)
print(len(ort_similarity_scores))
print("Cosine similarity:")
print(cosine_similarity_scores)
print(len(cosine_similarity_scores))

# spearman
from scipy.stats import spearmanr


coef, _ = spearmanr(ort_similarity_scores, cosine_similarity_scores)
print(f"Spearman coefficient: {coef}")



print(common_words)

